# ==========================================
# BoardingHub Server
# ==========================================

server.port=8080
server.address=0.0.0.0


# ==========================================
# PostgreSQL Database
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / Hibernate DDL Configuration
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# ==========================================
# Security / JWT Configuration
# ==========================================

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000


# ==========================================
# Spring Mail SMTP Configuration
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sulabodim@gmail.com
spring.mail.password=jcavndpthdgfozjb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# Google Maps Geocoding API Key Configuration
# ==========================================

google.maps.api.key=${GOOGLE_MAPS_API_KEY:}
